planning_plugin: ompl_interface/OMPLPlanner
request_adapters: default_planner_request_adapters/AddTimeOptimalParameterization
start_state_max_bounds_error: 0.1

planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.5
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.5
    goal_bias: 0.05
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    range: 0.5
    border_fraction: 0.5
    min_valid_path_fraction: 0.3
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
    range: 0.5
    border_fraction: 0.5
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.3
  KPIECEkConfigDefault:
    type: geometric::KPIECE
    range: 0.5
    goal_bias: 0.05
    border_fraction: 0.5
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.3
  # RRTkConfigDefault:
  #   type: geometric::RRT
  #   goal_bias: 0.05
  # RRTConnectkConfigDefault:
  #   type: geometric::RRTConnect
  # RRTstarkConfigDefault:
  #   type: geometric::RRTstar
  #   goal_bias: 0.05
  #   delay_collision_checking: 1

  RRTkConfigDefault:
    # type: geometric::RRT
    optimization_objective: MaximizeMinClearanceObjective
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  RRTstarkConfigDefault:
    # type: geometric::RRTstar
    optimization_objective: MaximizeMinClearanceObjective
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1

  TRRTkConfigDefault:
    # type: geometric::TRRT
    goal_bias: 0.05
    max_states_failed: 10
    temp_change_factor: 2.0
    min_temperature: 10e-10
    init_temperature: 10e-6
    frontier_threshold: 0.0
    frontierNodeRatio: 0.1
    k_constant: 0.0
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstarkConfigDefault:
    # type: geometric::PRMstar
    # type: geometric::PRM
    max_nearest_neighbors: 10

sim_ur10e:
  planner_configs:
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
  longest_valid_segment_fraction: 0.005