joint_limits:
  ur10e_base_to_robot_mount:
    has_acceleration_limits: true
    max_acceleration: 1.0
  ur10e_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ur10e_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ur10e_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ur10e_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ur10e_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ur10e_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0