/sim/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
        
    # Controller listesi
    sim_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    sim_io_and_status_controller:
      type: ur_controllers/GPIOController

    sim_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    sim_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    sim_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    sim_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    sim_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    sim_gripper_controller:
      type: forward_command_controller/ForwardCommandController



# Speed Scaling State Broadcaster
/sim/sim_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0

# Joint Trajectory Controller
/sim/sim_joint_trajectory_controller:
  ros__parameters:
    joints:
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      sim_ur10e_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Scaled Joint Trajectory Controller
/sim/sim_scaled_joint_trajectory_controller:
  ros__parameters:
    type: ur_controllers/ScaledJointTrajectoryController
    joints:
      - sim_ur10e_base_to_robot_mount
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: ""
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      sim_ur10e_base_to_robot_mount: { trajectory: 0.5, goal: 0.3 }
      sim_ur10e_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      sim_ur10e_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Forward Velocity Controller
/sim/sim_forward_velocity_controller:
  ros__parameters:
    joints:
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint
    interface_name: velocity

# Forward Position Controller
/sim/sim_forward_position_controller:
  ros__parameters:
    joints:
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint

# Gripper Controller
/sim/sim_gripper_controller:
  ros__parameters:
    joints:
      - sim_ur10e_gripper_joint
    interface_name: position
